// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v5.27.1
// source: kessel/inventory/v1/health.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInventoryHealthServiceGetLivez = "/api.kessel.inventory.v1.InventoryHealthService/GetLivez"
const OperationInventoryHealthServiceGetReadyz = "/api.kessel.inventory.v1.InventoryHealthService/GetReadyz"

type InventoryHealthServiceHTTPServer interface {
	GetLivez(context.Context, *GetLivezRequest) (*GetLivezResponse, error)
	GetReadyz(context.Context, *GetReadyzRequest) (*GetReadyzResponse, error)
}

func RegisterInventoryHealthServiceHTTPServer(s *http.Server, srv InventoryHealthServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/inventory/v1/livez", _InventoryHealthService_GetLivez0_HTTP_Handler(srv))
	r.GET("/api/inventory/v1/readyz", _InventoryHealthService_GetReadyz0_HTTP_Handler(srv))
}

func _InventoryHealthService_GetLivez0_HTTP_Handler(srv InventoryHealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLivezRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryHealthServiceGetLivez)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLivez(ctx, req.(*GetLivezRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLivezResponse)
		return ctx.Result(200, reply)
	}
}

func _InventoryHealthService_GetReadyz0_HTTP_Handler(srv InventoryHealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReadyzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryHealthServiceGetReadyz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReadyz(ctx, req.(*GetReadyzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReadyzResponse)
		return ctx.Result(200, reply)
	}
}

type InventoryHealthServiceHTTPClient interface {
	GetLivez(ctx context.Context, req *GetLivezRequest, opts ...http.CallOption) (rsp *GetLivezResponse, err error)
	GetReadyz(ctx context.Context, req *GetReadyzRequest, opts ...http.CallOption) (rsp *GetReadyzResponse, err error)
}

type InventoryHealthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInventoryHealthServiceHTTPClient(client *http.Client) InventoryHealthServiceHTTPClient {
	return &InventoryHealthServiceHTTPClientImpl{client}
}

func (c *InventoryHealthServiceHTTPClientImpl) GetLivez(ctx context.Context, in *GetLivezRequest, opts ...http.CallOption) (*GetLivezResponse, error) {
	var out GetLivezResponse
	pattern := "/api/inventory/v1/livez"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInventoryHealthServiceGetLivez))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InventoryHealthServiceHTTPClientImpl) GetReadyz(ctx context.Context, in *GetReadyzRequest, opts ...http.CallOption) (*GetReadyzResponse, error) {
	var out GetReadyzResponse
	pattern := "/api/inventory/v1/readyz"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInventoryHealthServiceGetReadyz))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
