apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kessel-debug-template
  namespace: kessel-${ENV}
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: kessel-debug
    name: kessel-debug
  spec:
    restartPolicy: OnFailure
    containers:
    - image: ${DEBUG_IMAGE}:${IMAGE_TAG}
      name: kessel-debug
      command: ["sleep"]
      args: ["${SLEEP_INTERVAL}"]
      imagePullPolicy: Always
      env:
      - name: ZED_ENDPOINT
        value: "kessel-relations-spicedb.kessel-${ENV}.svc:50051"
      - name: ZED_INSECURE
        value: "true"
      - name: RELATIONS_API_GRPC_ENDPOINT
        value: "kessel-relations-api.kessel-${ENV}.svc:9000"
      - name: RELATIONS_API_HTTP_ENDPOINT
        value: "kessel-relations-api.kessel-${ENV}.svc:8000"
      - name: INVENTORY_API_GRPC_ENDPOINT
        value: "kessel-inventory-api.kessel-${ENV}.svc:9000"
      - name: INVENTORY_API_HTTP_ENDPOINT
        value: "kessel-inventory-api.kessel-${ENV}.svc:8000"
      - name: ZED_TOKEN
        valueFrom:
          secretKeyRef:
            name: spicedb-config
            key: preshared_key
      - name: INVENTORY_SSO_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: kessel-sso-sa
            key: client-id
      - name: INVENTORY_SSO_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: kessel-sso-sa
            key: client-secret
      - name: INVENTORY_SSO_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: kessel-sso-sa
            key: url
      volumeMounts:
        - name: config-secret
          mountPath: /cdapp/
        - name: spicedb-secret
          mountPath: /spicedb/
        - name: kafka-ca-certs
          mountPath: "/kafka-ca-certs"
    volumes:
      - name: config-secret
        secret:
          secretName: kessel-inventory  # leverages inventory secret as it includes kafka info
          defaultMode: 420
      - name: spicedb-secret
        secret:
          secretName: kessel-relations-spicedb
          defaultMode: 420
      - name: kafka-ca-certs
        secret:
          secretName: ${CA_CERT_SECRET}
          optional: true
parameters:
  - name: ENV
    description: Target environment of the deployment (int, stage, or prod only)
    required: true
  - name: DEBUG_IMAGE
    description: Quay image name for the debug container
    value: quay.io/redhat-services-prod/project-kessel-tenant/kessel-debug
  - name: IMAGE_TAG
    description: Image tag for the debug container
    value: latest
  - name: CA_CERT_SECRET
    description: Name of the secret that contains the Kafka CA Cert (if applicable)
    required: true
    value: kessel-kafka-connect-config
  - name: SLEEP_INTERVAL
    description: How long should sleep run to keep the pod alive (in seconds)
    required: true
    value: "7200"
