// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: kessel/inventory/v1beta1/error.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A URI reference [RFC3986] that identifies the problem type.
	Type string `protobuf:"bytes,3575610,opt,name=type,proto3" json:"type,omitempty"`
	// A short, human-readable summary of the problem type.
	Title string `protobuf:"bytes,110371416,opt,name=title,proto3" json:"title,omitempty"`
	// The HTTP status code ([RFC7231], Section (6) generated by the origin server
	// for this occurrence of the problem.
	Status int32 `protobuf:"varint,355610639,opt,name=status,proto3" json:"status,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `protobuf:"bytes,261482417,opt,name=detail,proto3" json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.  It
	// may or may not yield further information if dereferenced.
	Instance string `protobuf:"bytes,18257046,opt,name=instance,proto3" json:"instance,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kessel_inventory_v1beta1_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Error) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Error) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

var File_kessel_inventory_v1beta1_error_proto protoreflect.FileDescriptor

var file_kessel_inventory_v1beta1_error_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6b, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x65, 0x73, 0x73,
	0x65, 0x6c, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x22, 0x8d, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x15,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0xba, 0x9e, 0xda, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0xd8,
	0xc4, 0xd0, 0x34, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x8f, 0xe0, 0xc8, 0xa9, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0xb1, 0xcf, 0xd7, 0x7c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x96, 0xa9, 0xda, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x42, 0x46, 0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x65, 0x73, 0x73,
	0x65, 0x6c, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x50, 0x01, 0x5a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x65, 0x73, 0x73,
	0x65, 0x6c, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kessel_inventory_v1beta1_error_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_error_proto_rawDescData = file_kessel_inventory_v1beta1_error_proto_rawDesc
)

func file_kessel_inventory_v1beta1_error_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_error_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_kessel_inventory_v1beta1_error_proto_rawDescData)
	})
	return file_kessel_inventory_v1beta1_error_proto_rawDescData
}

var file_kessel_inventory_v1beta1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta1_error_proto_goTypes = []any{
	(*Error)(nil), // 0: api.kessel.inventory.v1beta1.Error
}
var file_kessel_inventory_v1beta1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_error_proto_init() }
func file_kessel_inventory_v1beta1_error_proto_init() {
	if File_kessel_inventory_v1beta1_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kessel_inventory_v1beta1_error_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kessel_inventory_v1beta1_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta1_error_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_error_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta1_error_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_error_proto = out.File
	file_kessel_inventory_v1beta1_error_proto_rawDesc = nil
	file_kessel_inventory_v1beta1_error_proto_goTypes = nil
	file_kessel_inventory_v1beta1_error_proto_depIdxs = nil
}
