// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/inventory/v1beta1/k8s_policy_detail.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on K8SPolicyDetail with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *K8SPolicyDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on K8SPolicyDetail with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// K8SPolicyDetailMultiError, or nil if none found.
func (m *K8SPolicyDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *K8SPolicyDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Disabled

	if _, ok := K8SPolicyDetail_Severity_name[int32(m.GetSeverity())]; !ok {
		err := K8SPolicyDetailValidationError{
			field:  "Severity",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return K8SPolicyDetailMultiError(errors)
	}

	return nil
}

// K8SPolicyDetailMultiError is an error wrapping multiple validation errors
// returned by K8SPolicyDetail.ValidateAll() if the designated constraints
// aren't met.
type K8SPolicyDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m K8SPolicyDetailMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m K8SPolicyDetailMultiError) AllErrors() []error { return m }

// K8SPolicyDetailValidationError is the validation error returned by
// K8SPolicyDetail.Validate if the designated constraints aren't met.
type K8SPolicyDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e K8SPolicyDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e K8SPolicyDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e K8SPolicyDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e K8SPolicyDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e K8SPolicyDetailValidationError) ErrorName() string { return "K8SPolicyDetailValidationError" }

// Error satisfies the builtin error interface
func (e K8SPolicyDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sK8SPolicyDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = K8SPolicyDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = K8SPolicyDetailValidationError{}
