// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/inventory/v1beta1/reporter_data.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReporterData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReporterData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReporterData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReporterDataMultiError, or
// nil if none found.
func (m *ReporterData) ValidateAll() error {
	return m.validate(true)
}

func (m *ReporterData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReporterType

	// no validation rules for ReporterInstanceId

	if all {
		switch v := interface{}(m.GetFirstReported()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReporterDataValidationError{
					field:  "FirstReported",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReporterDataValidationError{
					field:  "FirstReported",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFirstReported()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReporterDataValidationError{
				field:  "FirstReported",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLastReported()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReporterDataValidationError{
					field:  "LastReported",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReporterDataValidationError{
					field:  "LastReported",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastReported()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReporterDataValidationError{
				field:  "LastReported",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ConsoleHref

	// no validation rules for ApiHref

	// no validation rules for LocalResourceId

	// no validation rules for ReporterVersion

	if len(errors) > 0 {
		return ReporterDataMultiError(errors)
	}

	return nil
}

// ReporterDataMultiError is an error wrapping multiple validation errors
// returned by ReporterData.ValidateAll() if the designated constraints aren't met.
type ReporterDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReporterDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReporterDataMultiError) AllErrors() []error { return m }

// ReporterDataValidationError is the validation error returned by
// ReporterData.Validate if the designated constraints aren't met.
type ReporterDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReporterDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReporterDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReporterDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReporterDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReporterDataValidationError) ErrorName() string { return "ReporterDataValidationError" }

// Error satisfies the builtin error interface
func (e ReporterDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReporterData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReporterDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReporterDataValidationError{}
