// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: kessel/inventory/v1beta1/hosts_service.proto

package v1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostsService_CreateRhelHost_FullMethodName = "/api.kessel.inventory.v1beta1.HostsService/CreateRhelHost"
	HostsService_UpdateRhelHost_FullMethodName = "/api.kessel.inventory.v1beta1.HostsService/UpdateRhelHost"
	HostsService_DeleteRhelHost_FullMethodName = "/api.kessel.inventory.v1beta1.HostsService/DeleteRhelHost"
)

// HostsServiceClient is the client API for HostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostsServiceClient interface {
	CreateRhelHost(ctx context.Context, in *CreateRhelHostRequest, opts ...grpc.CallOption) (*CreateRhelHostResponse, error)
	UpdateRhelHost(ctx context.Context, in *UpdateRhelHostRequest, opts ...grpc.CallOption) (*UpdateRhelHostResponse, error)
	DeleteRhelHost(ctx context.Context, in *DeleteRhelHostRequest, opts ...grpc.CallOption) (*DeleteRhelHostResponse, error)
}

type hostsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostsServiceClient(cc grpc.ClientConnInterface) HostsServiceClient {
	return &hostsServiceClient{cc}
}

func (c *hostsServiceClient) CreateRhelHost(ctx context.Context, in *CreateRhelHostRequest, opts ...grpc.CallOption) (*CreateRhelHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRhelHostResponse)
	err := c.cc.Invoke(ctx, HostsService_CreateRhelHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) UpdateRhelHost(ctx context.Context, in *UpdateRhelHostRequest, opts ...grpc.CallOption) (*UpdateRhelHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRhelHostResponse)
	err := c.cc.Invoke(ctx, HostsService_UpdateRhelHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) DeleteRhelHost(ctx context.Context, in *DeleteRhelHostRequest, opts ...grpc.CallOption) (*DeleteRhelHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRhelHostResponse)
	err := c.cc.Invoke(ctx, HostsService_DeleteRhelHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostsServiceServer is the server API for HostsService service.
// All implementations must embed UnimplementedHostsServiceServer
// for forward compatibility.
type HostsServiceServer interface {
	CreateRhelHost(context.Context, *CreateRhelHostRequest) (*CreateRhelHostResponse, error)
	UpdateRhelHost(context.Context, *UpdateRhelHostRequest) (*UpdateRhelHostResponse, error)
	DeleteRhelHost(context.Context, *DeleteRhelHostRequest) (*DeleteRhelHostResponse, error)
	mustEmbedUnimplementedHostsServiceServer()
}

// UnimplementedHostsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostsServiceServer struct{}

func (UnimplementedHostsServiceServer) CreateRhelHost(context.Context, *CreateRhelHostRequest) (*CreateRhelHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRhelHost not implemented")
}
func (UnimplementedHostsServiceServer) UpdateRhelHost(context.Context, *UpdateRhelHostRequest) (*UpdateRhelHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRhelHost not implemented")
}
func (UnimplementedHostsServiceServer) DeleteRhelHost(context.Context, *DeleteRhelHostRequest) (*DeleteRhelHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRhelHost not implemented")
}
func (UnimplementedHostsServiceServer) mustEmbedUnimplementedHostsServiceServer() {}
func (UnimplementedHostsServiceServer) testEmbeddedByValue()                      {}

// UnsafeHostsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostsServiceServer will
// result in compilation errors.
type UnsafeHostsServiceServer interface {
	mustEmbedUnimplementedHostsServiceServer()
}

func RegisterHostsServiceServer(s grpc.ServiceRegistrar, srv HostsServiceServer) {
	// If the following call pancis, it indicates UnimplementedHostsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostsService_ServiceDesc, srv)
}

func _HostsService_CreateRhelHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRhelHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).CreateRhelHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_CreateRhelHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).CreateRhelHost(ctx, req.(*CreateRhelHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_UpdateRhelHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRhelHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).UpdateRhelHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_UpdateRhelHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).UpdateRhelHost(ctx, req.(*UpdateRhelHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_DeleteRhelHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRhelHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).DeleteRhelHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_DeleteRhelHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).DeleteRhelHost(ctx, req.(*DeleteRhelHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostsService_ServiceDesc is the grpc.ServiceDesc for HostsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.kessel.inventory.v1beta1.HostsService",
	HandlerType: (*HostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRhelHost",
			Handler:    _HostsService_CreateRhelHost_Handler,
		},
		{
			MethodName: "UpdateRhelHost",
			Handler:    _HostsService_UpdateRhelHost_Handler,
		},
		{
			MethodName: "DeleteRhelHost",
			Handler:    _HostsService_DeleteRhelHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kessel/inventory/v1beta1/rhel_hosts_service.proto",
}
