// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/inventory/v1beta1/update_resource_relationship_by_urnhs_resources_parameter.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on
// UpdateResourceRelationshipByURNHsResourcesParameter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateResourceRelationshipByURNHsResourcesParameter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// UpdateResourceRelationshipByURNHsResourcesParameter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in
// UpdateResourceRelationshipByURNHsResourcesParameterMultiError, or nil if
// none found.
func (m *UpdateResourceRelationshipByURNHsResourcesParameter) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateResourceRelationshipByURNHsResourcesParameter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubjectResource

	// no validation rules for ObjectResource

	if len(errors) > 0 {
		return UpdateResourceRelationshipByURNHsResourcesParameterMultiError(errors)
	}

	return nil
}

// UpdateResourceRelationshipByURNHsResourcesParameterMultiError is an error
// wrapping multiple validation errors returned by
// UpdateResourceRelationshipByURNHsResourcesParameter.ValidateAll() if the
// designated constraints aren't met.
type UpdateResourceRelationshipByURNHsResourcesParameterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateResourceRelationshipByURNHsResourcesParameterMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateResourceRelationshipByURNHsResourcesParameterMultiError) AllErrors() []error { return m }

// UpdateResourceRelationshipByURNHsResourcesParameterValidationError is the
// validation error returned by
// UpdateResourceRelationshipByURNHsResourcesParameter.Validate if the
// designated constraints aren't met.
type UpdateResourceRelationshipByURNHsResourcesParameterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateResourceRelationshipByURNHsResourcesParameterValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e UpdateResourceRelationshipByURNHsResourcesParameterValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e UpdateResourceRelationshipByURNHsResourcesParameterValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e UpdateResourceRelationshipByURNHsResourcesParameterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateResourceRelationshipByURNHsResourcesParameterValidationError) ErrorName() string {
	return "UpdateResourceRelationshipByURNHsResourcesParameterValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateResourceRelationshipByURNHsResourcesParameterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateResourceRelationshipByURNHsResourcesParameter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateResourceRelationshipByURNHsResourcesParameterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateResourceRelationshipByURNHsResourcesParameterValidationError{}
