server:
  public_url: http://localhost:8000
  http:
    address: localhost:8000
  grpc:
    address: localhost:9000
  pprof:
    enabled: true
authn:
  authenticator:
    type: first_match
    chain:
      - type: guest
        enabled: true
authz:
  impl: allow-all
eventing:
  eventer: stdout
storage:
  max-serialization-retries: 10
  database: postgres
  postgres:
    host: localhost
    port: 5435
    user: inventory_api
    password: postgres
    dbname: inventory
  sqlite3:
    dsn: inventory.db
resources:
  schemaPath: "data/schema/resources"
  use_cache: true
consumer:
  enabled: false
log:
  level: "info"
  livez: true
  readyz: true
