server:
  public_url: http://localhost:8000
  http:
    address: localhost:8000
  grpc:
    address: localhost:9000
authn:
   allow-unauthenticated: true
authz:
  impl: allow-all
eventing:
  eventer: stdout
storage:
  disable-persistence: false
  database: sqlite3
  sqlite3:
    dsn: inventory.db
resources:
  schemaPath: "data/schema/resources"
  use_cache: true
consumer:
  enabled: false
log:
  level: "info"
  livez: true
  readyz: true
