server:
  http:
    address: localhost:8081
  grpc:
    address: localhost:9081
authn:
   allow-unauthenticated: true
authz:
  impl: kessel
  kessel:
    insecure-client: true
    url: localhost:9000
    enable_oidc_auth: false
eventing:
  eventer: stdout
  kafka:
storage:
  database: sqlite3
  sqlite3:
    dsn: inventory.db
  postgres:
    host: "localhost"
    port: "5432"
    user:
    password:
    dbname:
