server:
  public_url: http://localhost:8000
  http:
    address: localhost:8000
  grpc:
    address: localhost:9000
  pprof:
    enabled: true
authn:
   allow-unauthenticated: true
authz:
  impl: allow-all
eventing:
  eventer: stdout
storage:
  max-serialization-retries: 10
  database: sqlite3
  sqlite3:
    dsn: inventory.db
service:
  use_v1beta2_db: true
resources:
  schemaPath: "data/schema/resources"
  use_cache: true
consumer:
  enabled: false
log:
  level: "info"
  livez: true
  readyz: true
