server:
  public_url: http://localhost:8000
  http:
    address: localhost:8000
  grpc:
    address: localhost:9000
  pprof:
    enabled: true
authn:
  # This is a legacy field for backwards compatibility. 
  # Will be deprecated in the future. and replaced with the authenticator chain. 
  # Will be removed when the code is released to stage and prod and configs are updated there.
  allow-unauthenticated: true
  authenticator:
    type: first_match
    chain:
      - type: oidc
        enable: false
        transport:
          http: false
          grpc: false
        config:
          insecure-client: true
          authn-server-url: http://127.0.0.1:8085/realms/redhat-external
          skip-client-id-check: true
          skip-issuer-check: true
          principal-user-domain: localhost
      - type: x-rh-identity  # x-rh-identity header support - currently applicable for http transport only
        enable: true
        transport:
          http: false
          grpc: false   
      - type: allow-unauthenticated # This is a special authenticator that allows unauthenticated access - mainly for Local-dev/Test 
        enable: true
        transport:
          http: true
          grpc: true
authz:
  impl: allow-all
eventing:
  eventer: stdout
storage:
  max-serialization-retries: 10
  database: postgres
  postgres:
    host: localhost
    port: 5435
    user: inventory_api
    password: postgres
    dbname: inventory
  sqlite3:
    dsn: inventory.db
resources:
  schemaPath: "data/schema/resources"
  use_cache: true
consumer:
  enabled: false
log:
  level: "info"
  livez: true
  readyz: true
