FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7-1769056855 AS builder

ARG TARGETARCH
USER root
RUN microdnf install -y tar gzip make which gcc gcc-c++ cyrus-sasl-lib findutils git go-toolset

WORKDIR /workspace

COPY go.mod go.sum ./

ENV CGO_ENABLED 1
RUN go mod download

COPY api ./api
# Copy API files for gorm usage
COPY cmd ./cmd
COPY internal ./internal

COPY test/e2e .

RUN go mod tidy
RUN go test -c -o e2e-inventory-tests

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7-1769056855

COPY --from=builder /workspace/e2e-inventory-tests /usr/local/bin/

USER 1001
ENV PATH="$PATH:/usr/local/bin"
 # Run the e2e tests
CMD ["./usr/local/bin/e2e-inventory-tests", "-test.v", "-test.parallel=1"]
