FROM registry.access.redhat.com/hi/go:1.26.5-fips AS builder

WORKDIR /workspace

COPY go.mod go.sum ./

RUN go mod download

COPY api ./api
COPY cmd ./cmd
COPY internal ./internal

COPY test/e2e .

RUN go mod tidy
RUN go test -c -o e2e-inventory-tests

FROM registry.access.redhat.com/hi/core-runtime:2.43-openssl-fips
WORKDIR /

COPY --from=builder /workspace/e2e-inventory-tests /usr/local/bin/

USER 1001
ENV PATH="$PATH:/usr/local/bin"
CMD ["./usr/local/bin/e2e-inventory-tests", "-test.v", "-test.parallel=1"]
