FROM quay.io/strimzi/kafka:0.46.0-kafka-3.9.0
USER root:root
RUN microdnf install wget tar -y && \
    wget -O debezium-connector-postgres.tar.gz https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.5.4.Final/debezium-connector-postgres-2.5.4.Final-plugin.tar.gz && \
    tar -zxvf debezium-connector-postgres.tar.gz -C /opt/kafka/plugins/ && \
    microdnf clean all -y
USER 1001
