services:
  inventory-api:
    environment:
      INVENTORY_API_CONFIG: /inventory-api-compose.yaml
    build:
      dockerfile: Dockerfile
    volumes:
      - ./sso-inventory-api.yaml:/inventory-api-compose.yaml:ro,z
      - ./config/psks.yaml:/psks.yaml:ro,z
    command: ["serve"]
    restart: "always"
    ports:
      - "8081:8081"
      - "9081:9081"
    depends_on:
      - keycloak
    networks:
      - kessel

  invmigrate:
    environment:
      INVENTORY_API_CONFIG: /inventory-api-compose.yaml
    build:
      dockerfile: Dockerfile
    volumes:
      - ./sso-inventory-api.yaml:/inventory-api-compose.yaml:ro,z
    command: ["migrate"]
    restart: "on-failure"
    depends_on:
      - invdatabase
    networks:
      - kessel

  invdatabase:
    image: "postgres"
    command: ["-p", "5433","-c", "track_commit_timestamp=on"]
    hostname: invdatabase
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"
      - "PGPORT=5433"
    networks:
      - kessel

  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    command: "start-dev --http-port=8084 --db-url-port 5434 --import-realm"
    restart: "on-failure"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
    volumes:
      - ./myrealm.json:/opt/keycloak/data/import/myrealm.json:rw,z
    ports:
      - 8084:8084
    networks:
      - kessel

  database:
    image: "postgres"
    command: -c track_commit_timestamp=on
    hostname: database
    ports:
      - "5434:5434"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"
    networks:
      - kessel

networks:
  kessel:
    name: kessel
    external: true
