apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    max_connections = 100
    listen_addresses = '*'
    shared_buffers = 128MB
    work_mem = 4MB
    wal_level = logical
    log_destination = 'stderr'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invdatabase
  labels:
    app: invdatabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invdatabase
  template:
    metadata:
      labels:
        app: invdatabase
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          command: [ "docker-entrypoint.sh", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
          volumeMounts:
          - name: postgres-config
            mountPath: /etc/postgresql/postgresql.conf
            subPath: postgresql.conf
          env:
            - name: POSTGRES_DB
              value: spicedb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-api-config
                  key: db_password
          ports:
            - containerPort: 5432
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config

---
apiVersion: v1
kind: Service
metadata:
  name: invdatabase
  labels:
    app: invdatabase
spec:
  ports:
    - port: 5433
      targetPort: 5432
  selector:
    app: invdatabase
  type: ClusterIP
