#!/bin/bash

# Helpful script for capturing DB creds to interpolate into the
# Debezium Connector deployment since ephemeral Kafka Connect is not configured
# for the KubernetesSecretConfigProvider

DB_SECRET=$(oc get secret kessel-inventory-db -o json)

export DB_NAME=$(echo $DB_SECRET | jq -r '.data."db.name" | @base64d')
export DB_HOSTNAME=$(echo $DB_SECRET | jq -r '.data."db.host" | @base64d')
export DB_PORT=$(echo $DB_SECRET | jq -r '.data."db.port" | @base64d')
export DB_USER=$(echo $DB_SECRET | jq -r '.data."db.user" | @base64d')
export DB_PASSWORD=$(echo $DB_SECRET | jq -r '.data."db.password" | @base64d')
export KAFKA_CONNECT_INSTANCE=$(oc get kc -o jsonpath='{.items[*].metadata.name}')

