services:
  inventory-api:
    depends_on:
      - invdatabase
      - invmigrate
    environment:
      INVENTORY_API_CONFIG: /inventory-api-compose.yaml
    build:
      dockerfile: Dockerfile
      args:
        VERSION: dev
    volumes:
      - ./inventory-api-compose.yaml:/inventory-api-compose.yaml:ro,z
      - ./config/psks.yaml:/psks.yaml:ro,z
      - ./schema_cache.json:/schema_cache.json:rw,z
    command: ["serve"]
    restart: "always"
    ports:
      - "8081:8081"
      - "9081:9081"
    networks:
      - kessel

  invmigrate:
    environment:
      INVENTORY_API_CONFIG: /inventory-api-compose.yaml
    build:
      dockerfile: Dockerfile
      args:
        VERSION: dev
    volumes:
      - ./inventory-api-compose.yaml:/inventory-api-compose.yaml:ro,z
      - ./schema_cache.json:/schema_cache.json:rw,z
    command: ["migrate"]
    restart: "on-failure"
    depends_on:
      - invdatabase
    networks:
      - kessel

  invdatabase:
    image: "postgres"
    command: ["-p", "5433","-c", "track_commit_timestamp=on"]
    hostname: invdatabase
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"
      - "PGPORT=5433"
    networks:
      - kessel

networks:
  kessel:
    name: kessel
    external: true
