# This config is designed to run with Relations locally
# ports have been updated to prevent conflicts
# authz configured for local running relations binary
server:
  public_url: http://localhost:8081
  http:
    address: localhost:8081
  grpc:
    address: localhost:9091
authn:
   allow-unauthenticated: true
authz:
  impl: kessel
  kessel:
    insecure-client: true
    url: localhost:9000
    enable-oidc-auth: false
    principal-user-domain: 0.0.0.0:8084
eventing:
  eventer: stdout
  kafka:
storage:
  disable-persistence: false
  database: sqlite3
  sqlite3:
    dsn: inventory.db
log:
  level: "info"
  livez: true
  readyz: true
