server:
  public_url: http://localhost:8000
  http:
    address: localhost:8000
  grpc:
    address: localhost:9000
authn:
   allow-unauthenticated: true
authz:
  impl: allow-all
eventing:
  eventer: stdout
  kafka:
storage:
  max-serialization-retries: 10
  database: postgres
  postgres:
    host: localhost
    port: 5435
    user: inventory_api
    password: postgres
    dbname: inventory
schema:
  repository: in-memory
  in-memory:
    type: json
    path: schema_cache.json
log:
  level: "info"
  livez: true
  readyz: true


