server:
  public_url: http://localhost:8000
  http:
    address: localhost:8000
  grpc:
    address: localhost:9000
authn:
   allow-unauthenticated: true
authz:
  impl: allow-all
eventing:
  eventer: stdout
  kafka:
storage:
  disable-persistence: false
  database: sqlite3
  sqlite3:
    dsn: inventory.db
  postgres:
    host: "localhost"
    port: "5432"
    user:
    password:
    dbname:
resources:
  schemaPath: "data/schema/resources"
  use_cache: true
log:
  level: "info"
  livez: true
  readyz: true


