{
 "title": "Kessel - Inventory API",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values({job=\"kessel-inventory-api\"},operation)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "kafka_datasource", "label": "Kafka Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Inventory API - HTTP/Unary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Code Totals (By Operation)",
   "type": "table",
   "description": "over selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code,operation) (increase(server_requests_code_total{job=\"kessel-inventory-api\", operation=~\"$operation\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Status Codes Per Second",
   "type": "timeseries",
   "description": "over selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code)(rate(server_requests_code_total{job=\"kessel-inventory-api\", code!~\"200|0\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Requests below 250ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(server_requests_seconds_bucket_bucket{le=\"0.25\", operation=~\"$operation\", job=\"kessel-inventory-api\"}[5m])) by (operation)\n/\nsum(rate(server_requests_seconds_bucket_count{job=\"kessel-inventory-api\"}[5m])) by (operation)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile",
   "type": "timeseries",
   "description": "rate of requests in seconds at X percentile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(server_requests_seconds_bucket_bucket{operation=~\"$operation\", job=\"kessel-inventory-api\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(server_requests_seconds_bucket_bucket{operation=~\"$operation\", job=\"kessel-inventory-api\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "irate(server_requests_seconds_bucket_count{operation=~\"$operation\", job=\"kessel-inventory-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inventory API - Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Stream Status Code Totals",
   "type": "table",
   "description": "over selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (code,operation) (increase(grpc_server_streams_total{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Error Codes Per Second",
   "type": "timeseries",
   "description": "over selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (code)(rate(grpc_server_streams_total{job=\"kessel-inventory-api\", code!~\"200|0\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Streams First Response below 1s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_stream_first_response_duration_seconds_bucket{le=\"1.0\", job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[5m]))\n/\nsum(rate(grpc_server_stream_first_response_duration_seconds_count{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream First Response Latency Percentiles",
   "type": "timeseries",
   "description": "first response latency at X percentile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_stream_first_response_duration_seconds_bucket{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_stream_first_response_duration_seconds_bucket{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Streams Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inventory Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Active Consumers",
   "type": "stat",
   "description": "Number of active consumers (should match number of replicas, may not indicate they are actively consuming depending on partition count)",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(consumer_stats_state{state=\"up\", job=\"kessel-inventory-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Msgs in Queue",
   "type": "stat",
   "description": "Number of messages remaining in topic to be processed",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consumer_stats_replyq{job=\"kessel-inventory-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Rebalance",
   "type": "stat",
   "description": "How long since last rebalance occurred",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(consumer_stats_rebalance_age{job=\"kessel-inventory-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Lag (messages)",
   "type": "timeseries",
   "description": "Messages are committed in batches of ~10. Lag up to 10 messages can be expected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_sum_offset_lag_sum{consumer_group='inventory-consumer'}) by (topic)",
     "legendFormat": "{topic=\"{{topic}}\", group=\"{{group}}\"}"
    },
    {
     "expr": "kafka_consumergroup_group_topic_sum_lag{topic=~\"outbox.event.kessel.resources\"}",
     "legendFormat": "{topic=\"{{topic}}\", group=\"{{group}}\"}"
    }
   ]
  },
  {
   "title": "Rebalance Events",
   "type": "timeseries",
   "description": "Captures how many rebalance events have occurred over set interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(consumer_stats_rebalance_cnt_total{job=\"kessel-inventory-api\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msg_process_failures_total{job=\"kessel-inventory-api\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-api\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Error Rate",
   "type": "timeseries",
   "description": "Errors related to the Consumer and not message processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(consumer_consumer_errors_total{job=\"kessel-inventory-api\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-api\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Error Events",
   "type": "table",
   "description": "Recent Kafka Error Event Messages Processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "consumer_kafka_error_events_total{job=\"kessel-inventory-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Outbox Events",
   "type": "stat",
   "description": "(in $range)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kessel_inventory_outbox_event_writes_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "stat",
   "description": "(in $range)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "End to end replication lag",
   "type": "timeseries",
   "description": "Write-versus-processed rate delta (events/sec written minus events/sec consumed). A sustained positive value indicates a growing processing backlog.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(kessel_inventory_outbox_event_writes_total[3m])) - sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Serialization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Requests (overall)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(server_requests_code_total{job=\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Serialization Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "targets": [
    {
     "expr": "sum(rate(kessel_inventory_serialization_failures_total{job=\"kessel-inventory-api\"}[$__rate_interval]))",
     "legendFormat": "serialization failures/s"
    }
   ]
  },
  {
   "title": "Serialization Exhaustions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "targets": [
    {
     "expr": "sum(rate(kessel_inventory_serialization_exhaustions_total{job=\"kessel-inventory-api\"}[$__rate_interval]))",
     "legendFormat": "serialization exhaustions/s"
    }
   ]
  }
 ]
}