{
 "title": "Kessel Inventory - Kafka Connect",
 "description": "Monitor Apache Kafka Connect",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "openshift-customer-monitoring/kessel-kafka-connect-podmonitor"
   },
   {
    "name": "kafka_connector",
    "label": "KafkaConnector",
    "query": {
     "query": "label_values(kafka_connect_connector_status{job=\"$job\"},connector)"
    }
   },
   {
    "name": "connector_type",
    "label": "Connector Type",
    "query": {
     "query": "debezium_metrics_totalnumberofeventsseen"
    }
   },
   {
    "name": "connector_name",
    "label": "Connector Name",
    "query": {
     "query": "debezium_metrics_totalnumberofeventsseen{plugin=\"$connector_type\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Debezium - Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Source Record Poll Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_rate{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"}"
    }
   ]
  },
  {
   "title": "Task Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_status{job=\"$job\",connector=\"$kafka_connector\",status=\"running\"}"
    }
   ]
  },
  {
   "title": "Source Record Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_total{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"}",
     "legendFormat": "Total records polled"
    },
    {
     "expr": "kafka_connect_source_task_source_record_write_total{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"}",
     "legendFormat": "Total records written"
    }
   ]
  },
  { "title": "Debezium - Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Table count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totaltablecount{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Remaining tables",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_remainingtablecount{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotrunning{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotcompleted{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotaborted{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Total events received"
    },
    {
     "expr": "debezium_metrics_numberofeventsskipped{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Events skipped"
    }
   ]
  },
  {
   "title": "Rows scanned",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_rowsscanned{plugin=\"$connector_type\",name=\"$connector_name\"}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"$job\",connector=\"$kafka_connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\",connector=\"$kafka_connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\",connector=\"$kafka_connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\",connector=\"$kafka_connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\",connector=\"$kafka_connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\",connector=\"$kafka_connector\"})"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$kafka_connector\",status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$kafka_connector\",status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$kafka_connector\",status=\"paused\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "timeseries",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$kafka_connector\",status!=\"\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "timeseries",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\",connector=\"$kafka_connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{job=\"$job\"})",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"$job\",area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\"}[5m]))",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Network traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_node_incoming_byte_rate{container=\"kessel-kafka-connect-connect\"}",
     "legendFormat": "Incoming({{client}})"
    },
    {
     "expr": "kafka_connect_node_outgoing_byte_rate{container=\"kessel-kafka-connect-connect\"}",
     "legendFormat": "Outgoing({{client}})"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area='heap',container=\"kessel-kafka-connect-connect\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_max_bytes{area='heap',container=\"kessel-kafka-connect-connect\"}",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{container=\"kessel-kafka-connect-connect\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "jvm_threads_peak{container=\"kessel-kafka-connect-connect\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "jvm_threads_started_total{container=\"kessel-kafka-connect-connect\"}",
     "legendFormat": "Started in total"
    }
   ]
  },
  { "title": "Source task metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Source Record Write rate",
   "type": "timeseries",
   "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_write_rate{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Poll rate",
   "type": "timeseries",
   "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_rate{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count average",
   "type": "timeseries",
   "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kafka_connect_source_task_source_record_active_count{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count max",
   "type": "timeseries",
   "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_connect_source_task_source_record_active_count{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_avg_time_ms{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_max_time_ms{job=\"$job\",connector=\"$kafka_connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Worker rebalances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Total number of rebalances ",
   "type": "stat",
   "description": "Total number of rebalances (by instance)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_completed_rebalances_total{job=\"$job\"} >= 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance (by instance)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{job=\"$job\"} >= 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Task Errors metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "description": "Total number of failures seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_failures{job=\"$job\",connector=\"$kafka_connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "description": "Total number of errors seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_errors{job=\"$job\",connector=\"$kafka_connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "description": "Total number of records skipped by task",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_records_skipped{job=\"$job\",connector=\"$kafka_connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_errors_logged{job=\"$job\",connector=\"$kafka_connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries made by task",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_retries{job=\"$job\",connector=\"$kafka_connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{job=\"$job\",connector=\"$kafka_connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce failures",
   "type": "timeseries",
   "description": "Number of failed produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_failures{job=\"$job\",connector=\"$kafka_connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}