server:
  http:
    address: 0.0.0.0:8081
  grpc:
    address: 0.0.0.0:9081
authn:
  oidc:
    authn-server-url: http://keycloak:8084/realms/redhat-external
    skip-client-id-check: true
    skip-issuer-check: true
    principal-user-domain: localhost
authz:
  impl: kessel
  kessel:
    insecure-client: true
    url: relations-api:9000
    enable-oidc-auth: false
    principal-user-domain: 0.0.0.0:8084
eventing:
  eventer: stdout
  kafka:
storage:
  disable-persistence: false
  database: postgres
  sqlite3:
    dsn: inventory.db
  postgres:
    host: "invdatabase"
    port: "5433"
    user: "postgres"
    password: "yPsw5e6ab4bvAGe5H"
    dbname: "spicedb"
log:
  level: "info"
  livez: true
  readyz: true

