#!/bin/bash

# for feature branch "feature-RHCLOUD-38543"

export KAFKA_CONNECT_INSTANCE="inventory-kafka-connect"
export BOOTSTRAP_SERVER="inventory-kafka-kafka-bootstrap"

DB_SECRET=$(oc get secret kessel-inventory-db -o json 2> /dev/null)

if [[ ! -z "$DB_SECRET" ]] ; then
    export DB_NAME=$(echo $DB_SECRET | jq -r '.data."db.name" | @base64d')
    export DB_HOSTNAME=$(echo $DB_SECRET | jq -r '.data."db.host" | @base64d')
    export DB_PORT="5432"
    export LOCAL_DB_PORT="5432"
    export DB_USER=$(echo $DB_SECRET | jq -r '.data."db.user" | @base64d')
    export DB_PASSWORD=$(echo $DB_SECRET | jq -r '.data."db.password" | @base64d')
fi
