// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: kessel/inventory/v1beta1/resources/k8s_policy_detail.proto

package resources

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The kind of policy
type K8SPolicyDetail_Severity int32

const (
	K8SPolicyDetail_SEVERITY_UNSPECIFIED K8SPolicyDetail_Severity = 0
	K8SPolicyDetail_SEVERITY_OTHER       K8SPolicyDetail_Severity = 1
	K8SPolicyDetail_LOW                  K8SPolicyDetail_Severity = 2
	K8SPolicyDetail_MEDIUM               K8SPolicyDetail_Severity = 3
	K8SPolicyDetail_HIGH                 K8SPolicyDetail_Severity = 4
	K8SPolicyDetail_CRITICAL             K8SPolicyDetail_Severity = 5
)

// Enum value maps for K8SPolicyDetail_Severity.
var (
	K8SPolicyDetail_Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_OTHER",
		2: "LOW",
		3: "MEDIUM",
		4: "HIGH",
		5: "CRITICAL",
	}
	K8SPolicyDetail_Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_OTHER":       1,
		"LOW":                  2,
		"MEDIUM":               3,
		"HIGH":                 4,
		"CRITICAL":             5,
	}
)

func (x K8SPolicyDetail_Severity) Enum() *K8SPolicyDetail_Severity {
	p := new(K8SPolicyDetail_Severity)
	*p = x
	return p
}

func (x K8SPolicyDetail_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (K8SPolicyDetail_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_enumTypes[0].Descriptor()
}

func (K8SPolicyDetail_Severity) Type() protoreflect.EnumType {
	return &file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_enumTypes[0]
}

func (x K8SPolicyDetail_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use K8SPolicyDetail_Severity.Descriptor instead.
func (K8SPolicyDetail_Severity) EnumDescriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescGZIP(), []int{0, 0}
}

type K8SPolicyDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Defines if the policy is currently enabled or disabled across all targets
	Disabled bool                     `protobuf:"varint,270940797,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Severity K8SPolicyDetail_Severity `protobuf:"varint,404558592,opt,name=severity,proto3,enum=kessel.inventory.v1beta1.resources.K8SPolicyDetail_Severity" json:"severity,omitempty"`
}

func (x *K8SPolicyDetail) Reset() {
	*x = K8SPolicyDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SPolicyDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SPolicyDetail) ProtoMessage() {}

func (x *K8SPolicyDetail) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SPolicyDetail.ProtoReflect.Descriptor instead.
func (*K8SPolicyDetail) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescGZIP(), []int{0}
}

func (x *K8SPolicyDetail) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *K8SPolicyDetail) GetSeverity() K8SPolicyDetail_Severity {
	if x != nil {
		return x.Severity
	}
	return K8SPolicyDetail_SEVERITY_UNSPECIFIED
}

var File_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto protoreflect.FileDescriptor

var file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x6b, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x2f, 0x6b, 0x38, 0x73, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x6b, 0x65,
	0x73, 0x73, 0x65, 0x6c, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02,
	0x0a, 0x0f, 0x4b, 0x38, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x1e, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0xfd, 0xf4,
	0x98, 0x81, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x66, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x80, 0xa6,
	0xf4, 0xc0, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e, 0x6b, 0x65, 0x73, 0x73, 0x65, 0x6c,
	0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4b, 0x38, 0x73,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x65, 0x76,
	0x65, 0x72, 0x69, 0x74, 0x79, 0x42, 0x08, 0xba, 0x48, 0x05, 0x82, 0x01, 0x02, 0x10, 0x01, 0x52,
	0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x22, 0x65, 0x0a, 0x08, 0x53, 0x65, 0x76,
	0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54,
	0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x4f, 0x54, 0x48, 0x45,
	0x52, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x05,
	0x42, 0x86, 0x01, 0x0a, 0x32, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x6b, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x6b, 0x65,
	0x73, 0x73, 0x65, 0x6c, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x2f, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescData = file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDesc
)

func file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescData = protoimpl.X.CompressGZIP(file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescData)
	})
	return file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDescData
}

var file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_goTypes = []any{
	(K8SPolicyDetail_Severity)(0), // 0: kessel.inventory.v1beta1.resources.K8sPolicyDetail.Severity
	(*K8SPolicyDetail)(nil),       // 1: kessel.inventory.v1beta1.resources.K8sPolicyDetail
}
var file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_depIdxs = []int32{
	0, // 0: kessel.inventory.v1beta1.resources.K8sPolicyDetail.severity:type_name -> kessel.inventory.v1beta1.resources.K8sPolicyDetail.Severity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_init() }
func file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_init() {
	if File_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*K8SPolicyDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_depIdxs,
		EnumInfos:         file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_enumTypes,
		MessageInfos:      file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto = out.File
	file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_rawDesc = nil
	file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_goTypes = nil
	file_kessel_inventory_v1beta1_resources_k8s_policy_detail_proto_depIdxs = nil
}
