// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta1/resources/k8s_clusters_service.proto

package resources

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateK8SClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The k8s cluster to create in Kessel Asset Inventory
	K8SCluster    *K8SCluster `protobuf:"bytes,1,opt,name=k8s_cluster,proto3" json:"k8s_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateK8SClusterRequest) Reset() {
	*x = CreateK8SClusterRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateK8SClusterRequest) ProtoMessage() {}

func (x *CreateK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateK8SClusterRequest) GetK8SCluster() *K8SCluster {
	if x != nil {
		return x.K8SCluster
	}
	return nil
}

type CreateK8SClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateK8SClusterResponse) Reset() {
	*x = CreateK8SClusterResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateK8SClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateK8SClusterResponse) ProtoMessage() {}

func (x *CreateK8SClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateK8SClusterResponse.ProtoReflect.Descriptor instead.
func (*CreateK8SClusterResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescGZIP(), []int{1}
}

type UpdateK8SClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource to be updated will be defined by
	// \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
	// from the request body.
	K8SCluster    *K8SCluster `protobuf:"bytes,1,opt,name=k8s_cluster,proto3" json:"k8s_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateK8SClusterRequest) Reset() {
	*x = UpdateK8SClusterRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateK8SClusterRequest) ProtoMessage() {}

func (x *UpdateK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateK8SClusterRequest) GetK8SCluster() *K8SCluster {
	if x != nil {
		return x.K8SCluster
	}
	return nil
}

type UpdateK8SClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateK8SClusterResponse) Reset() {
	*x = UpdateK8SClusterResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateK8SClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateK8SClusterResponse) ProtoMessage() {}

func (x *UpdateK8SClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateK8SClusterResponse.ProtoReflect.Descriptor instead.
func (*UpdateK8SClusterResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescGZIP(), []int{3}
}

type DeleteK8SClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource to be deleted will be defined by
	// \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
	// from the request body.
	ReporterData  *ReporterData `protobuf:"bytes,1,opt,name=reporter_data,proto3" json:"reporter_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteK8SClusterRequest) Reset() {
	*x = DeleteK8SClusterRequest{}
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteK8SClusterRequest) ProtoMessage() {}

func (x *DeleteK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteK8SClusterRequest) GetReporterData() *ReporterData {
	if x != nil {
		return x.ReporterData
	}
	return nil
}

type DeleteK8SClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteK8SClusterResponse) Reset() {
	*x = DeleteK8SClusterResponse{}
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteK8SClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteK8SClusterResponse) ProtoMessage() {}

func (x *DeleteK8SClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteK8SClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteK8SClusterResponse) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescGZIP(), []int{5}
}

var File_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDesc = "" +
	"\n" +
	"=kessel/inventory/v1beta1/resources/k8s_clusters_service.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a4kessel/inventory/v1beta1/resources/k8s_cluster.proto\x1a6kessel/inventory/v1beta1/resources/reporter_data.proto\"k\n" +
	"\x17CreateK8sClusterRequest\x12P\n" +
	"\vk8s_cluster\x18\x01 \x01(\v2..kessel.inventory.v1beta1.resources.K8sClusterR\vk8s_cluster\"\x1a\n" +
	"\x18CreateK8sClusterResponse\"k\n" +
	"\x17UpdateK8sClusterRequest\x12P\n" +
	"\vk8s_cluster\x18\x01 \x01(\v2..kessel.inventory.v1beta1.resources.K8sClusterR\vk8s_cluster\"\x1a\n" +
	"\x18UpdateK8sClusterResponse\"y\n" +
	"\x17DeleteK8sClusterRequest\x12^\n" +
	"\rreporter_data\x18\x01 \x01(\v20.kessel.inventory.v1beta1.resources.ReporterDataB\x06\xbaH\x03\xc8\x01\x01R\rreporter_data\"\x1a\n" +
	"\x18DeleteK8sClusterResponse2\xf7\x04\n" +
	"\x17KesselK8sClusterService\x12\xc7\x01\n" +
	"\x10CreateK8sCluster\x12;.kessel.inventory.v1beta1.resources.CreateK8sClusterRequest\x1a<.kessel.inventory.v1beta1.resources.CreateK8sClusterResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/api/inventory/v1beta1/resources/k8s-clusters\x12\xc7\x01\n" +
	"\x10UpdateK8sCluster\x12;.kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest\x1a<.kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse\"8\x82\xd3\xe4\x93\x022:\x01*\x1a-/api/inventory/v1beta1/resources/k8s-clusters\x12\xc7\x01\n" +
	"\x10DeleteK8sCluster\x12;.kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest\x1a<.kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse\"8\x82\xd3\xe4\x93\x022:\x01**-/api/inventory/v1beta1/resources/k8s-clustersB\x86\x01\n" +
	"2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

var (
	file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDescData
}

var file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_goTypes = []any{
	(*CreateK8SClusterRequest)(nil),  // 0: kessel.inventory.v1beta1.resources.CreateK8sClusterRequest
	(*CreateK8SClusterResponse)(nil), // 1: kessel.inventory.v1beta1.resources.CreateK8sClusterResponse
	(*UpdateK8SClusterRequest)(nil),  // 2: kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest
	(*UpdateK8SClusterResponse)(nil), // 3: kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse
	(*DeleteK8SClusterRequest)(nil),  // 4: kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest
	(*DeleteK8SClusterResponse)(nil), // 5: kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse
	(*K8SCluster)(nil),               // 6: kessel.inventory.v1beta1.resources.K8sCluster
	(*ReporterData)(nil),             // 7: kessel.inventory.v1beta1.resources.ReporterData
}
var file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_depIdxs = []int32{
	6, // 0: kessel.inventory.v1beta1.resources.CreateK8sClusterRequest.k8s_cluster:type_name -> kessel.inventory.v1beta1.resources.K8sCluster
	6, // 1: kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest.k8s_cluster:type_name -> kessel.inventory.v1beta1.resources.K8sCluster
	7, // 2: kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest.reporter_data:type_name -> kessel.inventory.v1beta1.resources.ReporterData
	0, // 3: kessel.inventory.v1beta1.resources.KesselK8sClusterService.CreateK8sCluster:input_type -> kessel.inventory.v1beta1.resources.CreateK8sClusterRequest
	2, // 4: kessel.inventory.v1beta1.resources.KesselK8sClusterService.UpdateK8sCluster:input_type -> kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest
	4, // 5: kessel.inventory.v1beta1.resources.KesselK8sClusterService.DeleteK8sCluster:input_type -> kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest
	1, // 6: kessel.inventory.v1beta1.resources.KesselK8sClusterService.CreateK8sCluster:output_type -> kessel.inventory.v1beta1.resources.CreateK8sClusterResponse
	3, // 7: kessel.inventory.v1beta1.resources.KesselK8sClusterService.UpdateK8sCluster:output_type -> kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse
	5, // 8: kessel.inventory.v1beta1.resources.KesselK8sClusterService.DeleteK8sCluster:output_type -> kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_init() }
func file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_init() {
	if File_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto != nil {
		return
	}
	file_kessel_inventory_v1beta1_resources_k8s_cluster_proto_init()
	file_kessel_inventory_v1beta1_resources_reporter_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto = out.File
	file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_goTypes = nil
	file_kessel_inventory_v1beta1_resources_k8s_clusters_service_proto_depIdxs = nil
}
