// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta1/resources/resource_label.proto

package resources

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,106079,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,111972721,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLabel) Reset() {
	*x = ResourceLabel{}
	mi := &file_kessel_inventory_v1beta1_resources_resource_label_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLabel) ProtoMessage() {}

func (x *ResourceLabel) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_resources_resource_label_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLabel.ProtoReflect.Descriptor instead.
func (*ResourceLabel) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResourceLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_kessel_inventory_v1beta1_resources_resource_label_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDesc = "" +
	"\n" +
	"7kessel/inventory/v1beta1/resources/resource_label.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1bbuf/validate/validate.proto\"N\n" +
	"\rResourceLabel\x12\x1b\n" +
	"\x03key\x18\u07fc\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12 \n" +
	"\x05value\x18\xf1\xa2\xb25 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05valueB\x86\x01\n" +
	"2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

var (
	file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDescData
}

var file_kessel_inventory_v1beta1_resources_resource_label_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta1_resources_resource_label_proto_goTypes = []any{
	(*ResourceLabel)(nil), // 0: kessel.inventory.v1beta1.resources.ResourceLabel
}
var file_kessel_inventory_v1beta1_resources_resource_label_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_resources_resource_label_proto_init() }
func file_kessel_inventory_v1beta1_resources_resource_label_proto_init() {
	if File_kessel_inventory_v1beta1_resources_resource_label_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDesc), len(file_kessel_inventory_v1beta1_resources_resource_label_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta1_resources_resource_label_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_resources_resource_label_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta1_resources_resource_label_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_resources_resource_label_proto = out.File
	file_kessel_inventory_v1beta1_resources_resource_label_proto_goTypes = nil
	file_kessel_inventory_v1beta1_resources_resource_label_proto_depIdxs = nil
}
