// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta1/relationships/metadata.proto

package relationships

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kessel Asset Inventory generated identifier.
	Id string `protobuf:"bytes,3356,opt,name=id,proto3" json:"id,omitempty"`
	// The type of Resource relationship
	RelationshipType string `protobuf:"bytes,251000036,opt,name=relationship_type,proto3" json:"relationship_type,omitempty"`
	// Date and time when the inventory item was first reported.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3400,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// Date and time when the inventory item was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3401,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	// Date and time when the inventory item was deleted.
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,3402,opt,name=deleted_at,proto3" json:"deleted_at,omitempty"`
	// The org id in which this resource is a member for access control.  A
	// resource can only be a member of one org.
	OrgId         string `protobuf:"bytes,3500,opt,name=org_id,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_kessel_inventory_v1beta1_relationships_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta1_relationships_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Metadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Metadata) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Metadata) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

var File_kessel_inventory_v1beta1_relationships_metadata_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDesc = "" +
	"\n" +
	"5kessel/inventory/v1beta1/relationships/metadata.proto\x12&kessel.inventory.v1beta1.relationships\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x02\n" +
	"\bMetadata\x12\x14\n" +
	"\x02id\x18\x9c\x1a \x01(\tB\x03\xe0A\x03R\x02id\x124\n" +
	"\x11relationship_type\x18\xe4\xe9\xd7w \x01(\tB\x03\xe0A\x03R\x11relationship_type\x12@\n" +
	"\n" +
	"created_at\x18\xc8\x1a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"created_at\x12@\n" +
	"\n" +
	"updated_at\x18\xc9\x1a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updated_at\x12@\n" +
	"\n" +
	"deleted_at\x18\xca\x1a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"deleted_at\x12 \n" +
	"\x06org_id\x18\xac\x1b \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06org_idB\x8e\x01\n" +
	"6org.project_kessel.api.inventory.v1beta1.relationshipsP\x01ZRgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/relationshipsb\x06proto3"

var (
	file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDesc), len(file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDescData
}

var file_kessel_inventory_v1beta1_relationships_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta1_relationships_metadata_proto_goTypes = []any{
	(*Metadata)(nil),              // 0: kessel.inventory.v1beta1.relationships.Metadata
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kessel_inventory_v1beta1_relationships_metadata_proto_depIdxs = []int32{
	1, // 0: kessel.inventory.v1beta1.relationships.Metadata.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: kessel.inventory.v1beta1.relationships.Metadata.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: kessel.inventory.v1beta1.relationships.Metadata.deleted_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta1_relationships_metadata_proto_init() }
func file_kessel_inventory_v1beta1_relationships_metadata_proto_init() {
	if File_kessel_inventory_v1beta1_relationships_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDesc), len(file_kessel_inventory_v1beta1_relationships_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta1_relationships_metadata_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta1_relationships_metadata_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta1_relationships_metadata_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta1_relationships_metadata_proto = out.File
	file_kessel_inventory_v1beta1_relationships_metadata_proto_goTypes = nil
	file_kessel_inventory_v1beta1_relationships_metadata_proto_depIdxs = nil
}
