apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-global-hub-operator
  namespace: multicluster-global-hub
spec:
  template:
    spec:
      containers:
        - name: multicluster-global-hub-operator
          env:
          - name: RELATED_IMAGE_INVENTORY_API
            value: localhost/inventory-api:latest
