{
 "title": "Kessel Inventory - Kafka Connect",
 "description": "Monitor Apache Kafka Connect",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "connector", "label": "Connector name", "query": "kessel-inventory-api-connector" },
   {
    "name": "job",
    "label": "job",
    "query": "openshift-customer-monitoring/kessel-kafka-connect-podmonitor"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"$job\",connector=\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\",connector=\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\",connector=\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\",connector=\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\",connector=\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\",connector=\"$connector\"})"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$connector\",status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$connector\",status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$connector\",status=\"paused\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "timeseries",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{job=\"$job\",connector=\"$connector\",status!=\"\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "timeseries",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\",connector=\"$connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{job=\"$job\"})",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"$job\",area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\"}[5m]))",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  { "title": "Source task metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Source Record Write rate",
   "type": "timeseries",
   "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_write_rate{job=\"$job\",connector=\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Poll rate",
   "type": "timeseries",
   "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_rate{job=\"$job\",connector=\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count average",
   "type": "timeseries",
   "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kafka_connect_source_task_source_record_active_count{job=\"$job\",connector=\"$connector\",task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count max",
   "type": "timeseries",
   "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_connect_source_task_source_record_active_count{job=\"$job\",connector=\"$connector\",task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_avg_time_ms{job=\"$job\",connector=\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_max_time_ms{job=\"$job\",connector=\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Worker rebalances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "($instance) Total number of rebalances",
   "type": "stat",
   "description": "Total number of rebalances",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_completed_rebalances{job=\"$job\"} >= 0"
    }
   ]
  },
  {
   "title": "($instance) Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{job=\"$job\"} >= 0"
    }
   ]
  },
  {
   "title": "Rebalances average time",
   "type": "timeseries",
   "description": "Rebalances average time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_rebalance_avg_time_ms{job=\"$job\"}",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  { "title": "Task metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_avg{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "description": "Maximum size of the batches processed by the connector",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_max{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit success percentage",
   "type": "timeseries",
   "description": "Average percentage of the task’s offset commit attempts that succeeded",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "description": "The fraction of time this task has spent in the running state.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Task Errors metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "description": "Total number of failures seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_failures{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "description": "Total number of errors seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_errors{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "description": "Total number of records skipped by task",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_records_skipped{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_errors_logged{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries made by task",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_retries{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce failures",
   "type": "timeseries",
   "description": "Number of failed produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_failures{job=\"$job\",connector=\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}