{
 "title": "Kessel - Operations Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "route",
    "label": "routes",
    "query": {
     "query": "label_values(server_requests_code_total{operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}, operation)"
    }
   },
   {
    "name": "stream_route",
    "label": "streaming routes",
    "query": {
     "query": "label_values(grpc_server_streams_total{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}, operation)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "kessel-stage,kessel-prod" },
   { "name": "env", "label": "Env", "query": "stage,prod" }
  ]
 },
 "panels": [
  { "title": "Inventory Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job='kessel-inventory-api'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ container=\"kessel-inventory-api\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{ container=\"kessel-inventory-api\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container='kessel-inventory-api'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability (selected time)",
   "type": "stat",
   "description": "The percentage of time that the API is available (not returning 5xx errors or timeouts).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_requests_code_total{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__range])) / sum(increase(server_requests_code_total{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests (http/unary)",
   "type": "timeseries",
   "description": "Number of requests per second by response codes.",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (label_replace(rate(server_requests_code_total{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]), \"code\", \"200\", \"code\", \"0\"))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors (http/unary)",
   "type": "timeseries",
   "description": "The error percentage.",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(server_requests_code_total{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"0|2..\"}[$__rate_interval])) / sum(rate(server_requests_code_total{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "non-2xx/0"
    },
    {
     "expr": "sum(rate(server_requests_code_total{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code=~\"5..|14\"}[$__rate_interval])) / sum(rate(server_requests_code_total{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "5xx and timeout"
    }
   ]
  },
  {
   "title": "Duration (http/unary)",
   "type": "timeseries",
   "description": "The average request duration",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(server_requests_seconds_bucket_sum{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__rate_interval])) / sum(increase(server_requests_seconds_bucket_count{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__rate_interval]))",
     "legendFormat": "Avg. response duration"
    }
   ]
  },
  {
   "title": "Latency (< 1s)",
   "type": "stat",
   "description": "The percentage of time that the API responds within 1 second.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_requests_seconds_bucket_bucket{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\",le=\"1.0\"}[$__range])) / sum(increase(server_requests_seconds_bucket_count{job=~\"kessel-inventory-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Availability (streaming)",
   "type": "stat",
   "description": "The percentage of streams that complete without 5xx errors or timeouts.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_streams_total{job=\"kessel-inventory-api\",code!~\"5..|14\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__range])) / sum(increase(grpc_server_streams_total{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests (streaming)",
   "type": "timeseries",
   "description": "Number of gRPC streams opened per second by response code.",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (label_replace(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]), \"code\", \"200\", \"code\", \"0\"))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors (streaming)",
   "type": "timeseries",
   "description": "The error percentage for streaming RPCs.",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",code!~\"0|2..\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval])) / sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "non-2xx/0"
    },
    {
     "expr": "sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",code=~\"5..|14\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval])) / sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "5xx and timeout"
    }
   ]
  },
  {
   "title": "Duration (streaming first response)",
   "type": "timeseries",
   "description": "The average time from stream open to first server response.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_stream_first_response_duration_seconds_sum{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval])) / sum(increase(grpc_server_stream_first_response_duration_seconds_count{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "Avg. first response duration"
    }
   ]
  },
  {
   "title": "Latency (< 1s, streaming)",
   "type": "stat",
   "description": "The percentage of streams that receive their first response within 1 second.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_stream_first_response_duration_seconds_bucket{job=\"kessel-inventory-api\",le=\"1.0\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__range])) / sum(increase(grpc_server_stream_first_response_duration_seconds_count{job=\"kessel-inventory-api\",operation!~\".*[Ss]erver[Rr]eflection.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consumer Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msg_process_failures_total{job=\"kessel-inventory-api\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-api\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Error Rate",
   "type": "timeseries",
   "description": "Errors related to the Consumer and not message processing",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(consumer_consumer_errors_total{job=\"kessel-inventory-api\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-api\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-api\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Relations Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job='kessel-relations-api'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ container=\"kessel-relations-api\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{ container=\"kessel-relations-api\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container='kessel-relations-api'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability (selected time)",
   "type": "stat",
   "description": "The percentage of time that the API is available (not returning 5xx errors or timeouts).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_requests_code_total{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__range])) / sum(increase(server_requests_code_total{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Number of requests per second by response codes.",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (label_replace(rate(server_requests_code_total{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]), \"code\", \"200\", \"code\", \"0\"))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "The error percentage.",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(server_requests_code_total{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"0|2..\"}[$__rate_interval])) / sum(rate(server_requests_code_total{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "non-2xx/0"
    },
    {
     "expr": "sum(rate(server_requests_code_total{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code=~\"5..|14\"}[$__rate_interval])) / sum(rate(server_requests_code_total{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\"}[$__rate_interval]))",
     "legendFormat": "5xx and timeout"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "The average request duration",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(server_requests_seconds_bucket_sum{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__rate_interval])) / sum(increase(server_requests_seconds_bucket_count{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__rate_interval]))",
     "legendFormat": "Avg. response duration"
    }
   ]
  },
  {
   "title": "Latency (< 1s)",
   "type": "stat",
   "description": "The percentage of time that the API responds within 1 second.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_requests_seconds_bucket_bucket{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\",le=\"1.0\"}[$__range])) / sum(increase(server_requests_seconds_bucket_count{job=~\"kessel-relations-api\",operation!~\".*[Ll]ive[Zz].*|.*[Rr]eady[Zz].*|.*grpc.health.*|.*[Ss]erver[Rr]eflection.*\",code!~\"5..|14\"}[$__range]))"
    }
   ]
  },
  { "title": "SpiceDB Cluster Pods Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job='kessel-relations-spicedb'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container='spicedb'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Conditions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spicedb_operator_clusters_condition_count",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ container=\"spicedb\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{ container=\"spicedb\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Num Clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spicedb_operator_clusters_count",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Cluster Reconciliation Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spicedb_operator_clusters_status_collector_errors_count",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  { "title": "SpiceDB Operator Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=~'spicedb-operator.*'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"spicedb-operator\", container=\"spicedb-operator\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"spicedb-operator\", container=\"spicedb-operator\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container='spicedb-operator'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kessel Inventory Consumer Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job='kessel-inventory-consumer-service'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ container=\"kessel-inventory-consumer-service\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{ container=\"kessel-inventory-consumer-service\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container='kessel-inventory-consumer-service'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msg_process_failures_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-consumer-service\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Error Rate",
   "type": "timeseries",
   "description": "Errors related to the Consumer and not message processing",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(consumer_errors_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-consumer-service\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kessel Kafka Connect Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{pod=~'kessel-kafka-connect-connect.*'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"kessel-kafka-connect-$env\", container=\"kessel-kafka-connect-connect\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"kessel-kafka-connect-$env\", container=\"kessel-kafka-connect-connect\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container='kessel-kafka-connect-connect'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RBAC Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container='rbac-service'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"rbac-$env\", container=~\"rbac.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"rbac-$env\", container=~\"rbac.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container='rbac-service'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "repeat": "route",
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "stat",
     "description": "The percentage of time that the endpoint is available (not returning 5xx errors or timeouts).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code!~\"5..|14\"}[$__range])) / sum(increase(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 76 },
     "targets": [
      {
       "expr": "sum by (code) (label_replace(rate(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\"}[$__rate_interval]), \"code\", \"200\", \"code\", \"0\"))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 76 },
     "targets": [
      {
       "expr": "sum(rate(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code!~\"0|2..\"}[$__rate_interval])) / sum(rate(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\"}[$__rate_interval]))",
       "legendFormat": "non-2xx/0"
      },
      {
       "expr": "sum(rate(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code=~\"5..|14\"}[$__rate_interval])) / sum(rate(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\"}[$__rate_interval]))",
       "legendFormat": "5xx and timeout"
      },
      {
       "expr": "sum(rate(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code=~\"4..\"}[$__rate_interval])) / sum(rate(server_requests_code_total{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\"}[$__rate_interval]))",
       "legendFormat": "4xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "description": "The average request duration for successful requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 76 },
     "targets": [
      {
       "expr": "sum(increase(server_requests_seconds_bucket_sum{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code!~\"5..|14\"}[$__rate_interval])) / sum(increase(server_requests_seconds_bucket_count{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code!~\"5..|14\"}[$__rate_interval]))",
       "legendFormat": "Avg. response duration"
      }
     ]
    },
    {
     "title": "Latency (< 1s, http/unary)",
     "type": "stat",
     "description": "The percentage of time that the endpoint responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(server_requests_seconds_bucket_bucket{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code!~\"5..|14\",le=\"1.0\"}[$__range])) / sum(increase(server_requests_seconds_bucket_count{job=~\"kessel-inventory-api|kessel-relations-api\",operation=\"${route:raw}\",code!~\"5..|14\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "$stream_route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "repeat": "stream_route",
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (streaming)",
     "type": "stat",
     "description": "The percentage of time that the streaming endpoint is available (not returning 5xx errors or timeouts).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_streams_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\",code!~\"5..|14\"}[$__range])) / sum(increase(grpc_server_streams_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests (streaming)",
     "type": "timeseries",
     "description": "Number of gRPC streams opened per second by response code.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (code) (label_replace(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval]), \"code\", \"200\", \"code\", \"0\"))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors (streaming)",
     "type": "timeseries",
     "description": "The error percentage for streaming RPCs.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\",code!~\"0|2..\"}[$__rate_interval])) / sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval]))",
       "legendFormat": "non-2xx/0"
      },
      {
       "expr": "sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\",code=~\"5..|14\"}[$__rate_interval])) / sum(rate(grpc_server_streams_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration (streaming first response)",
     "type": "timeseries",
     "description": "The average time from stream open to first server response.",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_stream_first_response_duration_seconds_sum{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval])) / sum(increase(grpc_server_stream_first_response_duration_seconds_count{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval]))",
       "legendFormat": "Avg. first response duration"
      }
     ]
    },
    {
     "title": "Latency (< 1s, streaming)",
     "type": "stat",
     "description": "The percentage of streams that receive their first response within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_stream_first_response_duration_seconds_bucket{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\",le=\"1.0\"}[$__range])) / sum(increase(grpc_server_stream_first_response_duration_seconds_count{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Message rate (streaming)",
     "type": "timeseries",
     "description": "Rate of individual stream messages sent and received per second.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (direction) (rate(grpc_server_stream_messages_total{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval]))",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "Message duration (streaming)",
     "type": "timeseries",
     "description": "Average duration of individual stream message send/receive operations.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (direction) (rate(grpc_server_stream_message_duration_seconds_sum{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval])) / sum by (direction) (rate(grpc_server_stream_message_duration_seconds_count{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval]))",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "Message duration heatmap (streaming)",
     "type": "heatmap",
     "description": "Distribution of individual stream message send/receive durations.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_stream_message_duration_seconds_bucket{job=\"kessel-inventory-api\",operation=\"${stream_route:raw}\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}