name: buf-push
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    name: Check protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: bufbuild/buf-action@v1
        with:
          format: false
          lint: true
          breaking: false
          push: true
          input: "api"
          token: ${{ secrets.BUF_TOKEN }}
