// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/check_self_bulk_request.proto

package v1beta2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckSelfBulkRequestItem represents a single permission check for the caller
// (self) in a bulk request. The subject is derived from the caller's
// authenticated identity rather than being provided explicitly.
type CheckSelfBulkRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ResourceReference     `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSelfBulkRequestItem) Reset() {
	*x = CheckSelfBulkRequestItem{}
	mi := &file_kessel_inventory_v1beta2_check_self_bulk_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSelfBulkRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSelfBulkRequestItem) ProtoMessage() {}

func (x *CheckSelfBulkRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_check_self_bulk_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSelfBulkRequestItem.ProtoReflect.Descriptor instead.
func (*CheckSelfBulkRequestItem) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescGZIP(), []int{0}
}

func (x *CheckSelfBulkRequestItem) GetObject() *ResourceReference {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CheckSelfBulkRequestItem) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

// CheckSelfBulkRequest allows checking multiple permissions for the caller
// (self) in a single request. This is more efficient than making individual
// CheckSelf calls when verifying permissions for multiple
// resource-relation combinations.
type CheckSelfBulkRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*CheckSelfBulkRequestItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Consistency   *Consistency                `protobuf:"bytes,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSelfBulkRequest) Reset() {
	*x = CheckSelfBulkRequest{}
	mi := &file_kessel_inventory_v1beta2_check_self_bulk_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSelfBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSelfBulkRequest) ProtoMessage() {}

func (x *CheckSelfBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_check_self_bulk_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSelfBulkRequest.ProtoReflect.Descriptor instead.
func (*CheckSelfBulkRequest) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescGZIP(), []int{1}
}

func (x *CheckSelfBulkRequest) GetItems() []*CheckSelfBulkRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckSelfBulkRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

var File_kessel_inventory_v1beta2_check_self_bulk_request_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDesc = "" +
	"\n" +
	"6kessel/inventory/v1beta2/check_self_bulk_request.proto\x12\x18kessel.inventory.v1beta2\x1a\x1bbuf/validate/validate.proto\x1a1kessel/inventory/v1beta2/resource_reference.proto\x1a*kessel/inventory/v1beta2/consistency.proto\"\x8c\x01\n" +
	"\x18CheckSelfBulkRequestItem\x12K\n" +
	"\x06object\x18\x01 \x01(\v2+.kessel.inventory.v1beta2.ResourceReferenceB\x06\xbaH\x03\xc8\x01\x01R\x06object\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brelation\"\xb6\x01\n" +
	"\x14CheckSelfBulkRequest\x12U\n" +
	"\x05items\x18\x01 \x03(\v22.kessel.inventory.v1beta2.CheckSelfBulkRequestItemB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x05items\x12G\n" +
	"\vconsistency\x18\x02 \x01(\v2%.kessel.inventory.v1beta2.ConsistencyR\vconsistencyBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDesc), len(file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDescData
}

var file_kessel_inventory_v1beta2_check_self_bulk_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kessel_inventory_v1beta2_check_self_bulk_request_proto_goTypes = []any{
	(*CheckSelfBulkRequestItem)(nil), // 0: kessel.inventory.v1beta2.CheckSelfBulkRequestItem
	(*CheckSelfBulkRequest)(nil),     // 1: kessel.inventory.v1beta2.CheckSelfBulkRequest
	(*ResourceReference)(nil),        // 2: kessel.inventory.v1beta2.ResourceReference
	(*Consistency)(nil),              // 3: kessel.inventory.v1beta2.Consistency
}
var file_kessel_inventory_v1beta2_check_self_bulk_request_proto_depIdxs = []int32{
	2, // 0: kessel.inventory.v1beta2.CheckSelfBulkRequestItem.object:type_name -> kessel.inventory.v1beta2.ResourceReference
	0, // 1: kessel.inventory.v1beta2.CheckSelfBulkRequest.items:type_name -> kessel.inventory.v1beta2.CheckSelfBulkRequestItem
	3, // 2: kessel.inventory.v1beta2.CheckSelfBulkRequest.consistency:type_name -> kessel.inventory.v1beta2.Consistency
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_check_self_bulk_request_proto_init() }
func file_kessel_inventory_v1beta2_check_self_bulk_request_proto_init() {
	if File_kessel_inventory_v1beta2_check_self_bulk_request_proto != nil {
		return
	}
	file_kessel_inventory_v1beta2_resource_reference_proto_init()
	file_kessel_inventory_v1beta2_consistency_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDesc), len(file_kessel_inventory_v1beta2_check_self_bulk_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_check_self_bulk_request_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_check_self_bulk_request_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_check_self_bulk_request_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_check_self_bulk_request_proto = out.File
	file_kessel_inventory_v1beta2_check_self_bulk_request_proto_goTypes = nil
	file_kessel_inventory_v1beta2_check_self_bulk_request_proto_depIdxs = nil
}
