// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: kessel/inventory/v1beta2/check_service.proto

package v1beta2

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// KesselCheckServiceClient is the client API for KesselCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KesselCheckServiceClient interface {
}

type kesselCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKesselCheckServiceClient(cc grpc.ClientConnInterface) KesselCheckServiceClient {
	return &kesselCheckServiceClient{cc}
}

// KesselCheckServiceServer is the server API for KesselCheckService service.
// All implementations must embed UnimplementedKesselCheckServiceServer
// for forward compatibility.
type KesselCheckServiceServer interface {
	mustEmbedUnimplementedKesselCheckServiceServer()
}

// UnimplementedKesselCheckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKesselCheckServiceServer struct{}

func (UnimplementedKesselCheckServiceServer) mustEmbedUnimplementedKesselCheckServiceServer() {}
func (UnimplementedKesselCheckServiceServer) testEmbeddedByValue()                            {}

// UnsafeKesselCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KesselCheckServiceServer will
// result in compilation errors.
type UnsafeKesselCheckServiceServer interface {
	mustEmbedUnimplementedKesselCheckServiceServer()
}

func RegisterKesselCheckServiceServer(s grpc.ServiceRegistrar, srv KesselCheckServiceServer) {
	// If the following call pancis, it indicates UnimplementedKesselCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KesselCheckService_ServiceDesc, srv)
}

// KesselCheckService_ServiceDesc is the grpc.ServiceDesc for KesselCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KesselCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kessel.inventory.v1beta2.KesselCheckService",
	HandlerType: (*KesselCheckServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "kessel/inventory/v1beta2/check_service.proto",
}
