// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/relation_subject_reference.proto

package v1beta2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DEPRECATED: RelationSubjectReference is part of the legacy tuple-layer API.
// This type exists only for RBAC backward compatibility and will be removed.
// New code should use SubjectReference instead.
type RelationSubjectReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An optional relation which points to a set of subjects instead of the single subject.
	// e.g. "members" or "owners" of a group identified in `subject`.
	Relation      *string                  `protobuf:"bytes,1,opt,name=relation,proto3,oneof" json:"relation,omitempty"`
	Subject       *RelationObjectReference `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationSubjectReference) Reset() {
	*x = RelationSubjectReference{}
	mi := &file_kessel_inventory_v1beta2_relation_subject_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationSubjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationSubjectReference) ProtoMessage() {}

func (x *RelationSubjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_relation_subject_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationSubjectReference.ProtoReflect.Descriptor instead.
func (*RelationSubjectReference) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDescGZIP(), []int{0}
}

func (x *RelationSubjectReference) GetRelation() string {
	if x != nil && x.Relation != nil {
		return *x.Relation
	}
	return ""
}

func (x *RelationSubjectReference) GetSubject() *RelationObjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

var File_kessel_inventory_v1beta2_relation_subject_reference_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDesc = "" +
	"\n" +
	"9kessel/inventory/v1beta2/relation_subject_reference.proto\x12\x18kessel.inventory.v1beta2\x1a\x1bbuf/validate/validate.proto\x1a8kessel/inventory/v1beta2/relation_object_reference.proto\"\x9d\x01\n" +
	"\x18RelationSubjectReference\x12\x1f\n" +
	"\brelation\x18\x01 \x01(\tH\x00R\brelation\x88\x01\x01\x12S\n" +
	"\asubject\x18\x02 \x01(\v21.kessel.inventory.v1beta2.RelationObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\asubjectB\v\n" +
	"\t_relationBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDesc), len(file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDescData
}

var file_kessel_inventory_v1beta2_relation_subject_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta2_relation_subject_reference_proto_goTypes = []any{
	(*RelationSubjectReference)(nil), // 0: kessel.inventory.v1beta2.RelationSubjectReference
	(*RelationObjectReference)(nil),  // 1: kessel.inventory.v1beta2.RelationObjectReference
}
var file_kessel_inventory_v1beta2_relation_subject_reference_proto_depIdxs = []int32{
	1, // 0: kessel.inventory.v1beta2.RelationSubjectReference.subject:type_name -> kessel.inventory.v1beta2.RelationObjectReference
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_relation_subject_reference_proto_init() }
func file_kessel_inventory_v1beta2_relation_subject_reference_proto_init() {
	if File_kessel_inventory_v1beta2_relation_subject_reference_proto != nil {
		return
	}
	file_kessel_inventory_v1beta2_relation_object_reference_proto_init()
	file_kessel_inventory_v1beta2_relation_subject_reference_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDesc), len(file_kessel_inventory_v1beta2_relation_subject_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_relation_subject_reference_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_relation_subject_reference_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_relation_subject_reference_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_relation_subject_reference_proto = out.File
	file_kessel_inventory_v1beta2_relation_subject_reference_proto_goTypes = nil
	file_kessel_inventory_v1beta2_relation_subject_reference_proto_depIdxs = nil
}
