// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/relation_object_type.proto

package v1beta2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DEPRECATED: RelationObjectType is part of the legacy tuple-layer API.
// This type exists only for RBAC backward compatibility and will be removed.
// New code should use higher-level resource operations instead.
type RelationObjectType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationObjectType) Reset() {
	*x = RelationObjectType{}
	mi := &file_kessel_inventory_v1beta2_relation_object_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationObjectType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationObjectType) ProtoMessage() {}

func (x *RelationObjectType) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_relation_object_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationObjectType.ProtoReflect.Descriptor instead.
func (*RelationObjectType) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_relation_object_type_proto_rawDescGZIP(), []int{0}
}

func (x *RelationObjectType) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RelationObjectType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_kessel_inventory_v1beta2_relation_object_type_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_relation_object_type_proto_rawDesc = "" +
	"\n" +
	"3kessel/inventory/v1beta2/relation_object_type.proto\x12\x18kessel.inventory.v1beta2\x1a\x1bbuf/validate/validate.proto\"X\n" +
	"\x12RelationObjectType\x12%\n" +
	"\tnamespace\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnamespace\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04nameBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_relation_object_type_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_relation_object_type_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_relation_object_type_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_relation_object_type_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_relation_object_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_relation_object_type_proto_rawDesc), len(file_kessel_inventory_v1beta2_relation_object_type_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_relation_object_type_proto_rawDescData
}

var file_kessel_inventory_v1beta2_relation_object_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta2_relation_object_type_proto_goTypes = []any{
	(*RelationObjectType)(nil), // 0: kessel.inventory.v1beta2.RelationObjectType
}
var file_kessel_inventory_v1beta2_relation_object_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_relation_object_type_proto_init() }
func file_kessel_inventory_v1beta2_relation_object_type_proto_init() {
	if File_kessel_inventory_v1beta2_relation_object_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_relation_object_type_proto_rawDesc), len(file_kessel_inventory_v1beta2_relation_object_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_relation_object_type_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_relation_object_type_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_relation_object_type_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_relation_object_type_proto = out.File
	file_kessel_inventory_v1beta2_relation_object_type_proto_goTypes = nil
	file_kessel_inventory_v1beta2_relation_object_type_proto_depIdxs = nil
}
