// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/reporter_reference.proto

package v1beta2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReporterReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	InstanceId    *string                `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3,oneof" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReporterReference) Reset() {
	*x = ReporterReference{}
	mi := &file_kessel_inventory_v1beta2_reporter_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReporterReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReporterReference) ProtoMessage() {}

func (x *ReporterReference) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_reporter_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReporterReference.ProtoReflect.Descriptor instead.
func (*ReporterReference) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_reporter_reference_proto_rawDescGZIP(), []int{0}
}

func (x *ReporterReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReporterReference) GetInstanceId() string {
	if x != nil && x.InstanceId != nil {
		return *x.InstanceId
	}
	return ""
}

var File_kessel_inventory_v1beta2_reporter_reference_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_reporter_reference_proto_rawDesc = "" +
	"\n" +
	"1kessel/inventory/v1beta2/reporter_reference.proto\x12\x18kessel.inventory.v1beta2\x1a\x1bbuf/validate/validate.proto\"\xcf\x01\n" +
	"\x11ReporterReference\x12,\n" +
	"\x04type\x18\x01 \x01(\tB\x18\xbaH\x15r\x13\x10\x012\x0f^[A-Za-z0-9_]+$R\x04type\x12|\n" +
	"\vinstance_id\x18\x02 \x01(\tBV\xbaHSrQ2O(?i)^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$|^[A-Za-z][A-Za-z0-9._-]{0,255}$H\x00R\n" +
	"instanceId\x88\x01\x01B\x0e\n" +
	"\f_instance_idBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_reporter_reference_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_reporter_reference_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_reporter_reference_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_reporter_reference_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_reporter_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_reporter_reference_proto_rawDesc), len(file_kessel_inventory_v1beta2_reporter_reference_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_reporter_reference_proto_rawDescData
}

var file_kessel_inventory_v1beta2_reporter_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta2_reporter_reference_proto_goTypes = []any{
	(*ReporterReference)(nil), // 0: kessel.inventory.v1beta2.ReporterReference
}
var file_kessel_inventory_v1beta2_reporter_reference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_reporter_reference_proto_init() }
func file_kessel_inventory_v1beta2_reporter_reference_proto_init() {
	if File_kessel_inventory_v1beta2_reporter_reference_proto != nil {
		return
	}
	file_kessel_inventory_v1beta2_reporter_reference_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_reporter_reference_proto_rawDesc), len(file_kessel_inventory_v1beta2_reporter_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_reporter_reference_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_reporter_reference_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_reporter_reference_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_reporter_reference_proto = out.File
	file_kessel_inventory_v1beta2_reporter_reference_proto_goTypes = nil
	file_kessel_inventory_v1beta2_reporter_reference_proto_depIdxs = nil
}
