// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/representation_metadata.proto

package v1beta2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepresentationMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocalResourceId string                 `protobuf:"bytes,1,opt,name=local_resource_id,json=localResourceId,proto3" json:"local_resource_id,omitempty"`
	ApiHref         string                 `protobuf:"bytes,2,opt,name=api_href,json=apiHref,proto3" json:"api_href,omitempty"`
	ConsoleHref     *string                `protobuf:"bytes,3,opt,name=console_href,json=consoleHref,proto3,oneof" json:"console_href,omitempty"`
	ReporterVersion *string                `protobuf:"bytes,4,opt,name=reporter_version,json=reporterVersion,proto3,oneof" json:"reporter_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RepresentationMetadata) Reset() {
	*x = RepresentationMetadata{}
	mi := &file_kessel_inventory_v1beta2_representation_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepresentationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepresentationMetadata) ProtoMessage() {}

func (x *RepresentationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_representation_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepresentationMetadata.ProtoReflect.Descriptor instead.
func (*RepresentationMetadata) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_representation_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *RepresentationMetadata) GetLocalResourceId() string {
	if x != nil {
		return x.LocalResourceId
	}
	return ""
}

func (x *RepresentationMetadata) GetApiHref() string {
	if x != nil {
		return x.ApiHref
	}
	return ""
}

func (x *RepresentationMetadata) GetConsoleHref() string {
	if x != nil && x.ConsoleHref != nil {
		return *x.ConsoleHref
	}
	return ""
}

func (x *RepresentationMetadata) GetReporterVersion() string {
	if x != nil && x.ReporterVersion != nil {
		return *x.ReporterVersion
	}
	return ""
}

var File_kessel_inventory_v1beta2_representation_metadata_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_representation_metadata_proto_rawDesc = "" +
	"\n" +
	"6kessel/inventory/v1beta2/representation_metadata.proto\x12\x18kessel.inventory.v1beta2\x1a\x1bbuf/validate/validate.proto\"\xef\x01\n" +
	"\x16RepresentationMetadata\x123\n" +
	"\x11local_resource_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0flocalResourceId\x12\"\n" +
	"\bapi_href\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aapiHref\x12&\n" +
	"\fconsole_href\x18\x03 \x01(\tH\x00R\vconsoleHref\x88\x01\x01\x12.\n" +
	"\x10reporter_version\x18\x04 \x01(\tH\x01R\x0freporterVersion\x88\x01\x01B\x0f\n" +
	"\r_console_hrefB\x13\n" +
	"\x11_reporter_versionBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_representation_metadata_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_representation_metadata_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_representation_metadata_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_representation_metadata_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_representation_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_representation_metadata_proto_rawDesc), len(file_kessel_inventory_v1beta2_representation_metadata_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_representation_metadata_proto_rawDescData
}

var file_kessel_inventory_v1beta2_representation_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta2_representation_metadata_proto_goTypes = []any{
	(*RepresentationMetadata)(nil), // 0: kessel.inventory.v1beta2.RepresentationMetadata
}
var file_kessel_inventory_v1beta2_representation_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_representation_metadata_proto_init() }
func file_kessel_inventory_v1beta2_representation_metadata_proto_init() {
	if File_kessel_inventory_v1beta2_representation_metadata_proto != nil {
		return
	}
	file_kessel_inventory_v1beta2_representation_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_representation_metadata_proto_rawDesc), len(file_kessel_inventory_v1beta2_representation_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_representation_metadata_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_representation_metadata_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_representation_metadata_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_representation_metadata_proto = out.File
	file_kessel_inventory_v1beta2_representation_metadata_proto_goTypes = nil
	file_kessel_inventory_v1beta2_representation_metadata_proto_depIdxs = nil
}
