// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/resource_representations.proto

package v1beta2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceRepresentations struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *RepresentationMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Common        *structpb.Struct        `protobuf:"bytes,2,opt,name=common,proto3,oneof" json:"common,omitempty"`
	Reporter      *structpb.Struct        `protobuf:"bytes,3,opt,name=reporter,proto3,oneof" json:"reporter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRepresentations) Reset() {
	*x = ResourceRepresentations{}
	mi := &file_kessel_inventory_v1beta2_resource_representations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRepresentations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRepresentations) ProtoMessage() {}

func (x *ResourceRepresentations) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_resource_representations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRepresentations.ProtoReflect.Descriptor instead.
func (*ResourceRepresentations) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_resource_representations_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRepresentations) GetMetadata() *RepresentationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResourceRepresentations) GetCommon() *structpb.Struct {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *ResourceRepresentations) GetReporter() *structpb.Struct {
	if x != nil {
		return x.Reporter
	}
	return nil
}

var File_kessel_inventory_v1beta2_resource_representations_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_resource_representations_proto_rawDesc = "" +
	"\n" +
	"7kessel/inventory/v1beta2/resource_representations.proto\x12\x18kessel.inventory.v1beta2\x1a\x1cgoogle/protobuf/struct.proto\x1a6kessel/inventory/v1beta2/representation_metadata.proto\x1a\x1bbuf/validate/validate.proto\"\xf7\x01\n" +
	"\x17ResourceRepresentations\x12T\n" +
	"\bmetadata\x18\x01 \x01(\v20.kessel.inventory.v1beta2.RepresentationMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x124\n" +
	"\x06common\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\x06common\x88\x01\x01\x128\n" +
	"\breporter\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\breporter\x88\x01\x01B\t\n" +
	"\a_commonB\v\n" +
	"\t_reporterBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_resource_representations_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_resource_representations_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_resource_representations_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_resource_representations_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_resource_representations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_resource_representations_proto_rawDesc), len(file_kessel_inventory_v1beta2_resource_representations_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_resource_representations_proto_rawDescData
}

var file_kessel_inventory_v1beta2_resource_representations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta2_resource_representations_proto_goTypes = []any{
	(*ResourceRepresentations)(nil), // 0: kessel.inventory.v1beta2.ResourceRepresentations
	(*RepresentationMetadata)(nil),  // 1: kessel.inventory.v1beta2.RepresentationMetadata
	(*structpb.Struct)(nil),         // 2: google.protobuf.Struct
}
var file_kessel_inventory_v1beta2_resource_representations_proto_depIdxs = []int32{
	1, // 0: kessel.inventory.v1beta2.ResourceRepresentations.metadata:type_name -> kessel.inventory.v1beta2.RepresentationMetadata
	2, // 1: kessel.inventory.v1beta2.ResourceRepresentations.common:type_name -> google.protobuf.Struct
	2, // 2: kessel.inventory.v1beta2.ResourceRepresentations.reporter:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_resource_representations_proto_init() }
func file_kessel_inventory_v1beta2_resource_representations_proto_init() {
	if File_kessel_inventory_v1beta2_resource_representations_proto != nil {
		return
	}
	file_kessel_inventory_v1beta2_representation_metadata_proto_init()
	file_kessel_inventory_v1beta2_resource_representations_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_resource_representations_proto_rawDesc), len(file_kessel_inventory_v1beta2_resource_representations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_resource_representations_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_resource_representations_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_resource_representations_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_resource_representations_proto = out.File
	file_kessel_inventory_v1beta2_resource_representations_proto_goTypes = nil
	file_kessel_inventory_v1beta2_resource_representations_proto_depIdxs = nil
}
