// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/resource_reference.proto

package v1beta2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Reporter      *ReporterReference     `protobuf:"bytes,3,opt,name=reporter,proto3,oneof" json:"reporter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReference) Reset() {
	*x = ResourceReference{}
	mi := &file_kessel_inventory_v1beta2_resource_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReference) ProtoMessage() {}

func (x *ResourceReference) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_resource_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReference.ProtoReflect.Descriptor instead.
func (*ResourceReference) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_resource_reference_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceReference) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceReference) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceReference) GetReporter() *ReporterReference {
	if x != nil {
		return x.Reporter
	}
	return nil
}

var File_kessel_inventory_v1beta2_resource_reference_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_resource_reference_proto_rawDesc = "" +
	"\n" +
	"1kessel/inventory/v1beta2/resource_reference.proto\x12\x18kessel.inventory.v1beta2\x1a\x1bbuf/validate/validate.proto\x1a1kessel/inventory/v1beta2/reporter_reference.proto\"\xd7\x01\n" +
	"\x11ResourceReference\x12=\n" +
	"\rresource_type\x18\x01 \x01(\tB\x18\xbaH\x15r\x13\x10\x012\x0f^[A-Za-z0-9_]+$R\fresourceType\x12(\n" +
	"\vresource_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"resourceId\x12L\n" +
	"\breporter\x18\x03 \x01(\v2+.kessel.inventory.v1beta2.ReporterReferenceH\x00R\breporter\x88\x01\x01B\v\n" +
	"\t_reporterBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_resource_reference_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_resource_reference_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_resource_reference_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_resource_reference_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_resource_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_resource_reference_proto_rawDesc), len(file_kessel_inventory_v1beta2_resource_reference_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_resource_reference_proto_rawDescData
}

var file_kessel_inventory_v1beta2_resource_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta2_resource_reference_proto_goTypes = []any{
	(*ResourceReference)(nil), // 0: kessel.inventory.v1beta2.ResourceReference
	(*ReporterReference)(nil), // 1: kessel.inventory.v1beta2.ReporterReference
}
var file_kessel_inventory_v1beta2_resource_reference_proto_depIdxs = []int32{
	1, // 0: kessel.inventory.v1beta2.ResourceReference.reporter:type_name -> kessel.inventory.v1beta2.ReporterReference
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_resource_reference_proto_init() }
func file_kessel_inventory_v1beta2_resource_reference_proto_init() {
	if File_kessel_inventory_v1beta2_resource_reference_proto != nil {
		return
	}
	file_kessel_inventory_v1beta2_reporter_reference_proto_init()
	file_kessel_inventory_v1beta2_resource_reference_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_resource_reference_proto_rawDesc), len(file_kessel_inventory_v1beta2_resource_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_resource_reference_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_resource_reference_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_resource_reference_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_resource_reference_proto = out.File
	file_kessel_inventory_v1beta2_resource_reference_proto_goTypes = nil
	file_kessel_inventory_v1beta2_resource_reference_proto_depIdxs = nil
}
