// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kessel/inventory/v1beta2/response_pagination.proto

package v1beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponsePagination struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContinuationToken string                 `protobuf:"bytes,1,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResponsePagination) Reset() {
	*x = ResponsePagination{}
	mi := &file_kessel_inventory_v1beta2_response_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePagination) ProtoMessage() {}

func (x *ResponsePagination) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_inventory_v1beta2_response_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePagination.ProtoReflect.Descriptor instead.
func (*ResponsePagination) Descriptor() ([]byte, []int) {
	return file_kessel_inventory_v1beta2_response_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *ResponsePagination) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

var File_kessel_inventory_v1beta2_response_pagination_proto protoreflect.FileDescriptor

const file_kessel_inventory_v1beta2_response_pagination_proto_rawDesc = "" +
	"\n" +
	"2kessel/inventory/v1beta2/response_pagination.proto\x12\x18kessel.inventory.v1beta2\"C\n" +
	"\x12ResponsePagination\x12-\n" +
	"\x12continuation_token\x18\x01 \x01(\tR\x11continuationTokenBr\n" +
	"(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

var (
	file_kessel_inventory_v1beta2_response_pagination_proto_rawDescOnce sync.Once
	file_kessel_inventory_v1beta2_response_pagination_proto_rawDescData []byte
)

func file_kessel_inventory_v1beta2_response_pagination_proto_rawDescGZIP() []byte {
	file_kessel_inventory_v1beta2_response_pagination_proto_rawDescOnce.Do(func() {
		file_kessel_inventory_v1beta2_response_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_response_pagination_proto_rawDesc), len(file_kessel_inventory_v1beta2_response_pagination_proto_rawDesc)))
	})
	return file_kessel_inventory_v1beta2_response_pagination_proto_rawDescData
}

var file_kessel_inventory_v1beta2_response_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kessel_inventory_v1beta2_response_pagination_proto_goTypes = []any{
	(*ResponsePagination)(nil), // 0: kessel.inventory.v1beta2.ResponsePagination
}
var file_kessel_inventory_v1beta2_response_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_inventory_v1beta2_response_pagination_proto_init() }
func file_kessel_inventory_v1beta2_response_pagination_proto_init() {
	if File_kessel_inventory_v1beta2_response_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_inventory_v1beta2_response_pagination_proto_rawDesc), len(file_kessel_inventory_v1beta2_response_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kessel_inventory_v1beta2_response_pagination_proto_goTypes,
		DependencyIndexes: file_kessel_inventory_v1beta2_response_pagination_proto_depIdxs,
		MessageInfos:      file_kessel_inventory_v1beta2_response_pagination_proto_msgTypes,
	}.Build()
	File_kessel_inventory_v1beta2_response_pagination_proto = out.File
	file_kessel_inventory_v1beta2_response_pagination_proto_goTypes = nil
	file_kessel_inventory_v1beta2_response_pagination_proto_depIdxs = nil
}
