// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: kessel/inventory/v1beta2/streamed_list_service.proto

package v1beta2

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// KesselStreamedListServiceClient is the client API for KesselStreamedListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KesselStreamedListServiceClient interface {
}

type kesselStreamedListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKesselStreamedListServiceClient(cc grpc.ClientConnInterface) KesselStreamedListServiceClient {
	return &kesselStreamedListServiceClient{cc}
}

// KesselStreamedListServiceServer is the server API for KesselStreamedListService service.
// All implementations must embed UnimplementedKesselStreamedListServiceServer
// for forward compatibility.
type KesselStreamedListServiceServer interface {
	mustEmbedUnimplementedKesselStreamedListServiceServer()
}

// UnimplementedKesselStreamedListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKesselStreamedListServiceServer struct{}

func (UnimplementedKesselStreamedListServiceServer) mustEmbedUnimplementedKesselStreamedListServiceServer() {
}
func (UnimplementedKesselStreamedListServiceServer) testEmbeddedByValue() {}

// UnsafeKesselStreamedListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KesselStreamedListServiceServer will
// result in compilation errors.
type UnsafeKesselStreamedListServiceServer interface {
	mustEmbedUnimplementedKesselStreamedListServiceServer()
}

func RegisterKesselStreamedListServiceServer(s grpc.ServiceRegistrar, srv KesselStreamedListServiceServer) {
	// If the following call pancis, it indicates UnimplementedKesselStreamedListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KesselStreamedListService_ServiceDesc, srv)
}

// KesselStreamedListService_ServiceDesc is the grpc.ServiceDesc for KesselStreamedListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KesselStreamedListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kessel.inventory.v1beta2.KesselStreamedListService",
	HandlerType: (*KesselStreamedListServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "kessel/inventory/v1beta2/streamed_list_service.proto",
}
